name: Build AWS Infra

on:
  workflow_dispatch:

env:
  TF_VERSION: 1.6.6
  AWS_REGION: us-east-2

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform -chdir=terraform init

    - name: Plan Terraform Changes
      run: terraform -chdir=terraform plan -out=tfplan

    - name: Apply Terraform Changes
      if: github.event_name == 'workflow_dispatch'
      run: terraform -chdir=terraform apply -auto-approve tfplan
