name: Build AWS Infra

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Terraform
      run: |
        cd terraform && terraform init && terraform apply --auto-approve
